### ISSUE TITLE
Are you able to get this to work still?

### ISSUE THREAD

**Issue by mdance** [blakecrosby/pcfinancial-cli#1]
Hey, I'm writing my own financial tracking software, and was looking to leverage this to import my PC Financial transactions, are you still able to get this to work? 

It keeps erroring with:

Error: PC Financial Mobile Banking is currently unavailable.  We apologize for the inconvenience.  If you need assistance with an urgent financial transaction, please Contact Us.

**Comment by blakecrosby** [comment]
Michael,

Sorry for the delay in responding, I was out of town.

This is no longer supported. As of Nov 1st, PC Financial is no more.
